name: CI Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        name: Set up Python
      - run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        name: Install requirements
      - run: python run.py data/* ./web
        name: Build html pages
      - run: cp -r content/images web
        name: Copy content/images/*